# Generated by Django 5.1.3 on 2024-11-25 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='customers.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('pending', 'Pending'), ('confirmed', 'Awaiting Confirmation'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='registered', max_length=50),
        ),
    ]
