# Generated by Django 5.1.3 on 2024-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_updated_at_alter_discountcode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Awaiting Confirmation'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='registered', max_length=50),
        ),
    ]
