# Generated by Django 5.1.4 on 2025-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
