# Generated by Django 5.1.4 on 2025-01-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cartitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
