# Generated by Django 5.1.4 on 2025-01-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_customer_date_joined'),
        ('orders', '0009_orderitem_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.address'),
        ),
    ]
