# Generated by Django 5.1.4 on 2025-01-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
