# Generated by Django 5.1.4 on 2025-01-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_address_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_snapshot',
        ),
    ]
