# Generated by Django 5.1.4 on 2025-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_address_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Awaiting Confirmation'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='registered', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
