# Generated by Django 5.1.4 on 2025-01-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_status_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Awaiting Confirmation'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='registered', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
