# Generated by Django 5.1.3 on 2024-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='favicon',
            field=models.ImageField(blank=True, default='logos/favicon.png', null=True, upload_to='favicons/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default.png', null=True, upload_to='logos/'),
        ),
    ]
