version: '3.8'

services:
  # django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=onlineshop
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    depends_on:
      - db
      - redis

  # celery
  celery:
    build: .
    command: celery -A onlineshop worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  # celerybit
  celery-beat:
    build: .
    command: celery -A onlineshop beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  # redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # postgres
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=onlineshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: