# Generated by Django 5.1.3 on 2024-12-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='is_active',
        ),
    ]
