# Generated by Django 5.1.3 on 2024-12-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productattribute_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
