# Generated by Django 5.1.3 on 2024-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_address_id_alter_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='users/'),
        ),
    ]
