# Generated by Django 5.1.3 on 2024-11-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_max_otp_try_customer_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
