# Generated by Django 5.1.3 on 2024-12-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
    ]
