# Generated by Django 5.1.3 on 2024-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='max_otp_try',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_is_active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp_max_out',
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'مدیر محصولات'), ('supervisor', 'ناظر'), ('operator', 'اپراتور')], max_length=20, null=True),
        ),
    ]
