# Generated by Django 5.1.3 on 2024-12-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_max_otp_try_remove_customer_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, choices=[('Product Manager', 'مدیر محصولات'), ('Supervisor', 'ناظر'), ('Operator', 'اپراتور')], max_length=20, null=True),
        ),
    ]
