# Generated by Django 5.1.3 on 2024-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_remove_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
