# Generated by Django 5.1.4 on 2025-01-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_address_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='uuid',
        ),
    ]
