# Generated by Django 5.1.3 on 2024-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_otp_is_active_alter_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50),
            preserve_default=False,
        ),
    ]
