# Generated by Django 5.1.3 on 2024-12-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/'),
        ),
    ]
