# Generated by Django 5.1.3 on 2024-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='media/users/default.png', null=True, upload_to='users/'),
        ),
    ]
