# Generated by Django 5.1.3 on 2024-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, choices=[('operator', 'Operator'), ('product_manager', 'Product Manager'), ('supervisor', 'Supervisor')], max_length=20, null=True),
        ),
    ]
