# Generated by Django 5.1.3 on 2024-12-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi bi tablet', max_length=50),
            preserve_default=False,
        ),
    ]
